boats = "boats"
loads = "loads"
slips = 'slips'
states = 'states'
users = 'users'
oauth_endpoint = 'https://accounts.google.com/o/oauth2/v2/auth'
client_id = '96733170677-c2mstds04jlrshtkvgpqt83pq5vh74s9.apps.googleusercontent.com'
secret = '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'
scope = 'https://www.googleapis.com/auth/userinfo.profile'
redirect_uri = 'https://perezjos-project.uw.r.appspot.com/oauth'
token_endpoint = 'https://oauth2.googleapis.com/token'
people_url = 'https://people.googleapis.com/v1/people/me?personFields=names'
