boats = "boats"
loads = "loads"
slips = 'slips'
states = 'states'
oauth_endpoint = 'https://accounts.google.com/o/oauth2/v2/auth'
client_id = '775742854651-ghnrpc8e7t0ihmiavtvhpo157lkccviv.apps.googleusercontent.com'
secret = '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'
scope = 'https://www.googleapis.com/auth/userinfo.profile'
redirect_uri = 'https://hw7-perezjos.uw.r.appspot.com/oauth'
token_endpoint = 'https://oauth2.googleapis.com/token'
people_url = 'https://people.googleapis.com/v1/people/me?personFields=names'
